### PR TITLE
Update to grails 3.3.1.

### PR DESCRIPTION
**Pull request by avscj**
Hi,

I think I got this to work. I have checked all tests, fixed swagger integration and made a small change to the DomainReader to throw an Exception in case the binding returns errors. I have also added an example resource for the CLUD operations on a domain. Hope it is good for a merge

### CODE REVIEW

**Comment by avscj** [comment]
Hi,

Now that the CI is passing, I hope you can check and merge if all is good

**Comment by avscj** [comment]
Fixes [#34](https://github.com/budjb/grails-jaxrs/issues/34)

**Comment by aluismarte** [comment]
When is supposed to be release?

**Comment by tmysik** [comment]
Any news? This is blocking upgrading to Grails 3.3+, right?

**Comment by budjb** [comment]
This has been released. Thanks @avscj !

**Comment by avscj** [comment]
with great pleasure 😊

**Pull request merged**
